### PR TITLE
Create mono repo 

### PR DESCRIPTION
**Pull request by ironjan**
This pull request adds...
 * [jeo-contrib](https://github.com/jeo/jeo-contrib/) (including history) as a subfolder to this repository
 * `contrib` as submodule to the main `pom.xml`
  * Removes `mongo` from contrib build because of failing tests (See #101)
 * some content to the `README`
 * extends the `.gitignore`

It also fixes the Travis Config and updates the jdk version. Currently, the build is failing for 9 and 10 though (See #102).

**After merging this PR,** the `contrib` repository and some preparation could be [archived](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories). Preparation for achiving at https://github.com/jeo/jeo-contrib/pull/8 - then cleaning up the issues, finally archiving.

### CODE REVIEW

**Comment by jdeolive** [comment]
Nice work @ironjan . It looks like the travis build didn't pass the PR... do you still want me to merge this one?

**Comment by jdeolive** [comment]
Whoops, didn't mean to close :)

**Comment by ironjan** [comment]
Hi, yeah. I plan on fixing it - may take a while though because I'm not very proficient with travis ;)

**Comment by ironjan** [comment]
@jdeolive If you can kindly take another look. Finally found a working `.travis.yml` ;)

**Comment by jdeolive** [comment]
Nice work @ironjan !

**Pull request merged**
